# Hexo configuration to serve static snapshot from source/ and prevent overwriting online site

# Site
url: https://wondering-xu.github.io
root: /
permalink: posts/:year/:month/:day/:title/
theme: custom

# Post filename pattern to align with Notion Flow output
new_post_name: :year-:month-:day-:title.md

# Do not render static HTML and asset directories; copy as-is to public/
skip_render:
  - "index.html"
  - "about/**"
  - "guestbook/**"
  - "search/**"
  - "photos/**"
  - "css/**"
  - "assets/**"
  - "js/**"
  - "**/*.html"

# Disable local hexo deploy; deployments should be manual or via workflow
deploy:
  type: ''
